import sqlite3
import os
import sqlite_vec
from flask import g, current_app

def get_db():
    if 'db' not in g:
        db_path = current_app.config['DATABASE']
        os.makedirs(os.path.dirname(db_path), exist_ok=True)
        g.db = sqlite3.connect(db_path)
        g.db.enable_load_extension(True)
        sqlite_vec.load(g.db)
        g.db.enable_load_extension(False)
        g.db.row_factory = sqlite3.Row
    return g.db

def close_db(e=None):
    db = g.pop('db', None)
    if db is not None:
        db.close()

def init_db(app):
    app.teardown_appcontext(close_db)

    with app.app_context():
        db = get_db()
        db.execute('''
            CREATE TABLE IF NOT EXISTS videos (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                channel_id TEXT,
                channel_id_source TEXT,
                channel_name TEXT,
                channel_url TEXT,
                scraped_at TEXT,
                video_id TEXT UNIQUE NOT NULL,
                video_title TEXT NOT NULL,
                video_url TEXT,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        ''')

        db.execute('''
            CREATE TABLE IF NOT EXISTS transcripts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                video_id TEXT NOT NULL,
                content TEXT,
                indexed_at TEXT DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (video_id) REFERENCES videos (video_id) ON DELETE CASCADE
            )
        ''')

        db.execute('''
            CREATE TABLE IF NOT EXISTS jobs (
                id TEXT PRIMARY KEY,
                video_id TEXT NOT NULL,
                job_type TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pending',
                error_message TEXT,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                completed_at TEXT,
                FOREIGN KEY (video_id) REFERENCES videos (video_id) ON DELETE CASCADE
            )
        ''')

        # Create indexes for better query performance
        db.execute('CREATE INDEX IF NOT EXISTS idx_videos_video_id ON videos(video_id)')
        db.execute('CREATE INDEX IF NOT EXISTS idx_videos_scraped_at ON videos(scraped_at DESC)')
        db.execute('CREATE INDEX IF NOT EXISTS idx_videos_channel_id ON videos(channel_id)')
        db.execute('CREATE INDEX IF NOT EXISTS idx_transcripts_video_id ON transcripts(video_id)')
        db.execute('CREATE INDEX IF NOT EXISTS idx_jobs_video_id ON jobs(video_id)')
        db.execute('CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status)')

        db.execute('''
            CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        ''')

        # Add summary column to transcripts (idempotent migration)
        try:
            db.execute('ALTER TABLE transcripts ADD COLUMN summary TEXT')
        except Exception:
            pass  # Column already exists

        # Transcript chunks for embedding-based vector search
        db.execute('''
            CREATE TABLE IF NOT EXISTS transcript_chunks (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                video_id TEXT NOT NULL,
                chunk_index INTEGER NOT NULL,
                content TEXT NOT NULL,
                FOREIGN KEY (video_id) REFERENCES videos (video_id) ON DELETE CASCADE
            )
        ''')
        db.execute('CREATE INDEX IF NOT EXISTS idx_chunks_video_id ON transcript_chunks(video_id)')

        # vec0 virtual table for KNN search (768-dim float vectors)
        db.execute('''
            CREATE VIRTUAL TABLE IF NOT EXISTS vec_chunks USING vec0(
                chunk_id INTEGER PRIMARY KEY,
                embedding float[768]
            )
        ''')

        # Topic cluster assignments
        db.execute('''
            CREATE TABLE IF NOT EXISTS video_clusters (
                video_id TEXT PRIMARY KEY,
                cluster_id INTEGER NOT NULL,
                FOREIGN KEY (video_id) REFERENCES videos (video_id) ON DELETE CASCADE
            )
        ''')

        # Cluster metadata (labels generated by Gemini)
        db.execute('''
            CREATE TABLE IF NOT EXISTS cluster_labels (
                cluster_id INTEGER PRIMARY KEY,
                label TEXT NOT NULL,
                video_count INTEGER DEFAULT 0,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        ''')

        # Seed default settings (INSERT OR IGNORE keeps existing values)
        db.execute(
            "INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)",
            ('transcription_provider', 'assemblyai')
        )
        default_model = os.environ.get('GEMINI_MODEL', 'gemini-2.5-flash')
        db.execute(
            "INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)",
            ('gemini_model', default_model)
        )
        db.execute(
            "INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)",
            ('profile_name', 'BookMarkManager User')
        )
        db.execute(
            "INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)",
            ('profile_subtitle', 'YouTube Bookmark Collection')
        )

        db.commit()
